branch: master
language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
env:
- CI=true
script:
- npm run build
deploy:
  provider: npm
  email: 286630571@qq.com
  api_key:
    secure: IP5JElzURzJfc6B0LFYcMlqJa1bz8FD+XAHOVDD5ZB0jtEZ4QRG/dSrPJARTSEsgrrs7VDgZvSeZXdKPAjV37b79+2DS+/j7Ek/kTWQFFU4vjIMVtfo5074HWnYmzPvCQUZX5VO3tYBShYl8DBfeFrkbK41geqkXAbqSp0hY53w5KufNFnJBdbGK6sJtZcoBmuJPRGQLsd0mCEyDCrmXNFMwtkAG/imGENgJTKe5c6G+Wgx1wtVzte+gsWKdNrqcEUyXKHobjN/O+b8ISU7tMTj7JxL3X76eA0LrZXFGTjsgmY9tZgcwf0h7/wkndK7B/vY/V0HyhnUdL+j45PaO460O4VIxsYtGaAHZ+IOPD4/prVHJd137elWu/FVRXWGi3r30VF8QMSeyK5E/jNG65m+c45L16OuZRHoeSN0/q7mAUq5r/+MhnsikNMWmwP+4y2iUDKPNdC2n+JhQ49R7oxGhST1hKoql7xUPqm1T1Z8Mtldxvvm2Stv2D2qCO5OVgB8eDSQ/L/IMREYp6ngW9NPbmRNsixzlU2vloBXPgyDi7sPLYvn/W/XOx4wttVR59C8odPu+IOZf7xCK1U3mZXomY44mN6jcMEeUV/OlW0hjqm8n6XlCGS5rzwhyvkv8bfoFb8cEwLzsRoJZBPE8czwcbBAhBeJ9jIeAsF8k4H8=
  skip_cleanup: 'true'
